import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Navbar from './Component/Navbar/Navbar'
import Footer from './Component/Footer/Footer'
import LandingPage from './Component/Landing/LandingPage'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>BuyOne Online Shoping : Wear The Style</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />

      </Head>
      <main>
          <div className="midImg">
            <img src="https://uploads-ssl.webflow.com/5d6fe845a10b7881ddcc9c9c/5f1e921ec61f6152848b639c_1.jpg" className='w-full ' alt="" />
          </div>
        <LandingPage/>
      </main>
    </>
  )
}
